### ISSUE TITLE
Add hover color to the header components

### ISSUE THREAD

**Issue by Jai-Solania-29** [SuperAayush/Zomato-Clone#107]
### Suggestion

Add hover color to the header components on the Investors Relation Page https://superaayush.github.io/Zomato-Clone/Investor-Relation.html
Take reference from https://www.zomato.com/investor-relations

Current Behaviour:

![image](https://user-images.githubusercontent.com/90816300/192854566-cfc29ecf-f009-44e5-bc09-db900ac0a353.png)

Expected Behaviour:

![Screenshot 2022-09-28 232149](https://user-images.githubusercontent.com/90816300/192854790-634aadac-8eeb-4997-8e16-8e5d4a58ec6c.png)

**Comment by NisooJadhav** [comment]
I can do that too, please assign me.

**Comment by developer-irfan** [comment]
@Jai-Solania-29 I would like to work on this issue.

**Comment by SuperAayush** [comment]
Great!!
@developer-irfan assigning you the issue!!
