### ISSUE TITLE
Add Investor Relations Page

### ISSUE THREAD

**Issue by Jai-Solania-29** [SuperAayush/Zomato-Clone#97]
### Suggestion

Add Investor Relations Page to the Website.
You can take reference from here: https://www.zomato.com/investor-relations

![image](https://user-images.githubusercontent.com/90816300/185316212-fa5d3d04-5be5-4487-b5ec-1cd37bc6e970.png)

![image](https://user-images.githubusercontent.com/90816300/185316618-fd418c37-7867-458f-a6be-0bca318863c5.png)

![image](https://user-images.githubusercontent.com/90816300/185316886-5ad8c0bc-8c9a-4e7c-9062-33bdaaf1f571.png)

**Comment by hemant-sw** [comment]
Hey! @Jai-Solania-29 I want to work on that issue can you assign me?

**Comment by Jai-Solania-29** [comment]
Hey @hemant-sw, Thanks for showing interest. You can start working on the Issue 😃.
